on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Deploy to Cyon
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: giacomobuetler.com
        server-dir: public_html/gmbh/app/wp-content/themes
        username: giacomob
        password: ${{ secrets.ftp_password }}
        protocol: ftp
        port: 21
